### PR TITLE
cxx: fix build with CARGO_TARGET_DIR set

### LINKED ISSUE #2335: `cargo check` fails in cxx demo if `CARGO_TARGET_DIR` is set
I get an error that looks like this:
```
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/include" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/crate" "-I" "." "-I" "../../../target/cxxbridge/demo/src" "-Wall" "-Wextra" "-std=c++14" "-o" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/a9655d8c113f2a3f-main.rs.o" "-c" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/sources/demo/src/main.rs.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/include" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/crate" "-I" "." "-I" "../../../target/cxxbridge/demo/src" "-Wall" "-Wextra" "-std=c++14" "-o" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/src/blobstore.o" "-c" "src/blobstore.cc"
  cargo:warning=src/blobstore.cc:2:10: fatal error: main.rs.h: No such file or directory

  cargo:warning=    2 | #include "main.rs.h"

  cargo:warning=      |          ^~~~~~~~~~~

  cargo:warning=compilation terminated.

  exit status: 1

  --- stderr

  CXX include path:
    /var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/include
    /var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/crate


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/include" "-I" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/cxxbridge/crate" "-I" "." "-I" "../../../target/cxxbridge/demo/src" "-Wall" "-Wextra" "-std=c++14" "-o" "/var/cache/cargo/target/release/build/demo-4ab9609d61ec3bdd/out/src/blobstore.o" "-c" "src/blobstore.cc" with args "c++" did not execute successfully (status code exit status: 1).
```

### PR DESCRIPTION
**Pull request by fw-immunant**
Fixes #2335. This `build.rs` file is already ours rather than matching the [upstream one](https://github.com/dtolnay/cxx/blob/master/demo/build.rs), so I think further changes are fine--stop me if not!

### CODE REVIEW

**Comment by mgeisler** [comment]
> Fixes #2335. This `build.rs` file is already ours rather than matching the [upstream one](https://github.com/dtolnay/cxx/blob/master/demo/build.rs), so I think further changes are fine--stop me if not!

Alright, I had honestly no idea what we had customized the build file :smile:

Thanks a lot for improving it, I only think we should add a comment explaining what this does.

File: third_party/cxx/blobstore/build.rs [hunk 1]
```diff
@@ -1,9 +1,16 @@
 fn main() {
+    let src_dir = {
```
Comment (mgeisler) [inline third_party/cxx/blobstore/build.rs:2]:
```suggestion
    // Handle $CARGO_TARGET_DIR being set.
    let src_dir = {
```

**Review by mgeisler — APPROVED** [review]

File: third_party/cxx/blobstore/build.rs (hunk 1 above)
Comment (mgeisler) [reply third_party/cxx/blobstore/build.rs:2]: Looking at this, you could consider writing it more directly as

```rust
// Handle $CARGO_TARGET_DIR being set.
let mut src_dir = std::env::var_os("CARGO_TARGET_DIR").unwrap_or("../../../target".into());
src_dir.push("/cxxbridge/demo/src");
```

Also, do you know how this relates to the `$OUT_DIR` variable which [Cargo sets](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates)?

Comment (fw-immunant) [reply third_party/cxx/blobstore/build.rs]: Done.

As I understand it, `$OUT_DIR` refers to a temporary directory, and is an output of Cargo; `$CARGO_TARGET_DIR` is an input to Cargo and might change what `$OUT_DIR` ends up being (but I'm not sure, I don't touch build scripts often... unless they break).
