### PR TITLE
Uninstall old mdbook-linkcheck while installing project tools.

### LINKED ISSUE #2773: link-check causing some build errors after 2024 update
After #2658, `cargo xtask build` (or`mdbook build`) is failing with the error mentioned here: https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/92. This can be fixed by removing the `[output.linkcheck]` section from book.toml (since I believe we're now using linkcheck2?).

However after that, the exclusions in the `[output.linkcheck2]` section don't seem to work, and building results in errors like `File not found: comprehensive-rust.pdf`.

### PR DESCRIPTION
**Pull request by egithinji**
Fixes #2773 .

### CODE REVIEW

File: xtask/src/main.rs [hunk 1]
```diff
@@ -128,9 +129,35 @@ fn install_tools() -> Result<()> {
...
     Ok(())
 }
 
+fn uninstall_mdbook_linkcheck() {
+    println!("Uninstalling old mdbook-linkcheck if installed...");
+    let output = Command::new(env!("CARGO"))
+        .arg("uninstall")
+        .arg("mdbook-linkcheck")
+        .output()
+        .expect("Failed to execute cargo uninstall mdbook-exerciser");
```
Comment (qwandor) [inline xtask/src/main.rs]: Typo, this should be mdbook-linkcheck.

**Review by qwandor — APPROVED** [review]

File: xtask/src/main.rs (hunk 1 above)
Comment (egithinji) [reply xtask/src/main.rs]: Ah good catch thanks.
