### PR TITLE
Fix safe FFI exercise on macOS

### LINKED ISSUE #570: Safe FFI exercise: `dirent` layout is different on Mac OS
The [safe FFI wrapper exercise](https://google.github.io/comprehensive-rust/exercises/day-3/safe-ffi-wrapper.html) uses the wrong layout on Mac OS.

### PR DESCRIPTION
**Pull request by schultetwin1**
Use the macOS definition of dirent.

Fixes #570

### CODE REVIEW

File: src/exercises/day-3/safe-ffi-wrapper.rs [hunk 1]
```diff
@@ -33,6 +36,18 @@ mod ffi {
         pub d_name: [c_char; 256],
     }
 
+    // Layout as per man entry for dirent
+    #[repr(C)]
+    #[cfg(target_os = "macos")]
```
Comment (mgeisler) [inline src/exercises/day-3/safe-ffi-wrapper.rs:41]: Great! Let's apply the attributes in the same ordre as above:

```suggestion
    #[cfg(target_os = "macos")]
    #[repr(C)]
```

**Review by mgeisler — APPROVED** [review]
